//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationClient.WinSvcReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WinSvcReference.ITaskHelper")]
    public interface ITaskHelper {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskHelper/BackupRepo", ReplyAction="http://tempuri.org/ITaskHelper/BackupRepoResponse")]
        void BackupRepo(string url, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskHelper/BackupRepo", ReplyAction="http://tempuri.org/ITaskHelper/BackupRepoResponse")]
        System.Threading.Tasks.Task BackupRepoAsync(string url, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskHelperChannel : AutomationClient.WinSvcReference.ITaskHelper, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskHelperClient : System.ServiceModel.ClientBase<AutomationClient.WinSvcReference.ITaskHelper>, AutomationClient.WinSvcReference.ITaskHelper {
        
        public TaskHelperClient() {
        }
        
        public TaskHelperClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskHelperClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskHelperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskHelperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void BackupRepo(string url, string path) {
            base.Channel.BackupRepo(url, path);
        }
        
        public System.Threading.Tasks.Task BackupRepoAsync(string url, string path) {
            return base.Channel.BackupRepoAsync(url, path);
        }
    }
}
