//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationClient.TaskServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskServiceReference.IGitHelper")]
    public interface IGitHelper {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGitHelper/BackupRepo", ReplyAction="http://tempuri.org/IGitHelper/BackupRepoResponse")]
        void BackupRepo(string url, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGitHelper/BackupRepo", ReplyAction="http://tempuri.org/IGitHelper/BackupRepoResponse")]
        System.Threading.Tasks.Task BackupRepoAsync(string url, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGitHelperChannel : AutomationClient.TaskServiceReference.IGitHelper, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GitHelperClient : System.ServiceModel.ClientBase<AutomationClient.TaskServiceReference.IGitHelper>, AutomationClient.TaskServiceReference.IGitHelper {
        
        public GitHelperClient() {
        }
        
        public GitHelperClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GitHelperClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GitHelperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GitHelperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void BackupRepo(string url, string path) {
            base.Channel.BackupRepo(url, path);
        }
        
        public System.Threading.Tasks.Task BackupRepoAsync(string url, string path) {
            return base.Channel.BackupRepoAsync(url, path);
        }
    }
}
